# Generated by Django 5.0.7 on 2024-08-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrossPostSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExifData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_position', models.CharField(blank=True, max_length=10, null=True)),
                ('source_type', models.CharField(blank=True, max_length=10, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('focal_length', models.CharField(blank=True, max_length=10, null=True)),
                ('lens_model', models.CharField(blank=True, max_length=100, null=True)),
                ('software', models.CharField(blank=True, max_length=20, null=True)),
                ('scene_type', models.IntegerField(blank=True, null=True)),
                ('lens_make', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time_digitized', models.DateTimeField(blank=True, null=True)),
                ('date_time_original', models.DateTimeField(blank=True, null=True)),
                ('aperture', models.CharField(blank=True, max_length=10, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=20, null=True)),
                ('metering_mode', models.IntegerField(blank=True, null=True)),
                ('scene_capture_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('creation_timestamp', models.DateTimeField()),
                ('title', models.TextField(blank=True, null=True)),
                ('is_profile_picture', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('cross_post_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.crosspostsource')),
                ('media_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.memorymetadata')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creation_timestamp', models.DateTimeField()),
                ('is_sensitive', models.BooleanField(default=False)),
                ('media', models.ManyToManyField(to='gallery.media')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_camera_metadata', models.BooleanField()),
                ('exif_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_metadata', to='gallery.exifdata')),
            ],
        ),
        migrations.AddField(
            model_name='memorymetadata',
            name='photo_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photometadata'),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField()),
                ('creation_timestamp', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('cross_post_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.crosspostsource')),
                ('memory_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.memorymetadata')),
            ],
        ),
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_camera_metadata', models.BooleanField()),
                ('exif_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_metadata', to='gallery.exifdata')),
            ],
        ),
        migrations.AddField(
            model_name='memorymetadata',
            name='video_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.videometadata'),
        ),
    ]
