# Generated by Django 5.0.7 on 2024-08-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exifdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exifdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
