# Generated by Django 5.0.7 on 2024-08-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_exifdata_latitude_exifdata_longitude'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemoryMetadata',
            new_name='MediaMetadata',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='memory_metadata',
            new_name='media_metadata',
        ),
    ]
