# Generated by Django 5.0.7 on 2024-08-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_memorymetadata_mediametadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='type',
            field=models.CharField(choices=[('story', 'Story'), ('post', 'Post')], default=('post', 'Post'), max_length=12),
        ),
    ]
