# Generated by Django 5.0.7 on 2024-08-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_memory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='type',
            field=models.CharField(choices=[('story', 'Story'), ('post', 'Post'), ('reel', 'Reel')], default=('post', 'Post'), max_length=12),
        ),
    ]
